# Generated by Django 5.2.9 on 2025-12-31 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.UUIDField(db_index=True, unique=True)),
                ('source', models.CharField(choices=[('fitbit', 'Fitbit'), ('garmin', 'Garmin'), ('oura', 'Oura'), ('apple_health', 'Apple Health'), ('cronometer', 'Cronometer'), ('myfitnesspal', 'MyFitnessPal'), ('manual', 'Manual Entry')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file_name', models.CharField(blank=True, max_length=255)),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('records_processed', models.IntegerField(default=0)),
                ('records_created', models.IntegerField(default=0)),
                ('records_skipped', models.IntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='import_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='BloodworkResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_date', models.DateField(db_index=True)),
                ('biomarker', models.CharField(db_index=True, max_length=100)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=30)),
                ('ref_range_low', models.FloatField(blank=True, null=True)),
                ('ref_range_high', models.FloatField(blank=True, null=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_type', models.CharField(blank=True, choices=[('high', 'High'), ('low', 'Low')], max_length=10)),
                ('lab_name', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloodwork_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-test_date', 'biomarker'],
                'indexes': [models.Index(fields=['user', 'biomarker', 'test_date'], name='core_bloodw_user_id_3f50d1_idx'), models.Index(fields=['biomarker', 'test_date'], name='core_bloodw_biomark_34b9bc_idx')],
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('fitbit', 'Fitbit'), ('garmin', 'Garmin'), ('oura', 'Oura'), ('apple_health', 'Apple Health'), ('cronometer', 'Cronometer'), ('myfitnesspal', 'MyFitnessPal'), ('manual', 'Manual Entry')], db_index=True, max_length=50)),
                ('metric_type', models.CharField(choices=[('steps', 'Steps'), ('distance', 'Distance'), ('calories_burned', 'Calories Burned'), ('active_minutes', 'Active Minutes'), ('floors_climbed', 'Floors Climbed'), ('heart_rate', 'Heart Rate'), ('resting_heart_rate', 'Resting Heart Rate'), ('hrv', 'Heart Rate Variability'), ('sleep_duration', 'Sleep Duration'), ('sleep_deep', 'Deep Sleep'), ('sleep_light', 'Light Sleep'), ('sleep_rem', 'REM Sleep'), ('sleep_awake', 'Time Awake'), ('sleep_score', 'Sleep Score'), ('weight', 'Weight'), ('body_fat', 'Body Fat Percentage'), ('spo2', 'Blood Oxygen (SpO2)'), ('skin_temp', 'Skin Temperature'), ('stress_score', 'Stress Score'), ('readiness_score', 'Readiness Score')], db_index=True, max_length=50)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('date', models.DateField(blank=True, db_index=True, null=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('import_batch_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['source', 'metric_type', 'timestamp'], name='core_health_source_22c65a_idx'), models.Index(fields=['metric_type', 'date'], name='core_health_metric__0842db_idx'), models.Index(fields=['user', 'metric_type', 'timestamp'], name='core_health_user_id_fd1344_idx')],
            },
        ),
        migrations.CreateModel(
            name='NutritionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('fitbit', 'Fitbit'), ('garmin', 'Garmin'), ('oura', 'Oura'), ('apple_health', 'Apple Health'), ('cronometer', 'Cronometer'), ('myfitnesspal', 'MyFitnessPal'), ('manual', 'Manual Entry')], max_length=50)),
                ('date', models.DateField(db_index=True)),
                ('calories', models.FloatField(blank=True, null=True)),
                ('protein_g', models.FloatField(blank=True, null=True)),
                ('carbs_g', models.FloatField(blank=True, null=True)),
                ('fat_g', models.FloatField(blank=True, null=True)),
                ('fiber_g', models.FloatField(blank=True, null=True)),
                ('sugar_g', models.FloatField(blank=True, null=True)),
                ('sodium_mg', models.FloatField(blank=True, null=True)),
                ('potassium_mg', models.FloatField(blank=True, null=True)),
                ('vitamin_d_iu', models.FloatField(blank=True, null=True)),
                ('iron_mg', models.FloatField(blank=True, null=True)),
                ('magnesium_mg', models.FloatField(blank=True, null=True)),
                ('micronutrients', models.JSONField(blank=True, default=dict)),
                ('water_ml', models.FloatField(blank=True, null=True)),
                ('alcohol_g', models.FloatField(blank=True, null=True)),
                ('caffeine_mg', models.FloatField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('import_batch_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='core_nutrit_user_id_4f242f_idx')],
            },
        ),
        migrations.CreateModel(
            name='SleepLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('fitbit', 'Fitbit'), ('garmin', 'Garmin'), ('oura', 'Oura'), ('apple_health', 'Apple Health'), ('cronometer', 'Cronometer'), ('myfitnesspal', 'MyFitnessPal'), ('manual', 'Manual Entry')], max_length=50)),
                ('source_log_id', models.CharField(blank=True, max_length=100)),
                ('date_of_sleep', models.DateField(db_index=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField()),
                ('minutes_asleep', models.IntegerField(blank=True, null=True)),
                ('minutes_awake', models.IntegerField(blank=True, null=True)),
                ('deep_sleep_minutes', models.IntegerField(blank=True, null=True)),
                ('light_sleep_minutes', models.IntegerField(blank=True, null=True)),
                ('rem_sleep_minutes', models.IntegerField(blank=True, null=True)),
                ('efficiency', models.IntegerField(blank=True, null=True)),
                ('sleep_score', models.IntegerField(blank=True, null=True)),
                ('stages_data', models.JSONField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('import_batch_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sleep_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_of_sleep'],
                'indexes': [models.Index(fields=['user', 'date_of_sleep'], name='core_sleepl_user_id_b4627f_idx'), models.Index(fields=['source', 'source_log_id'], name='core_sleepl_source_38eccb_idx')],
            },
        ),
    ]
