# Generated by Django 5.2.7 on 2025-12-31 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('calories', models.FloatField(blank=True, null=True)),
                ('protein_g', models.FloatField(blank=True, null=True)),
                ('carbs_g', models.FloatField(blank=True, null=True)),
                ('fat_g', models.FloatField(blank=True, null=True)),
                ('fiber_g', models.FloatField(blank=True, null=True)),
                ('sodium_mg', models.FloatField(blank=True, null=True)),
                ('sleep_duration_min', models.IntegerField(blank=True, null=True)),
                ('sleep_minutes_asleep', models.IntegerField(blank=True, null=True)),
                ('sleep_minutes_awake', models.IntegerField(blank=True, null=True)),
                ('deep_sleep_min', models.IntegerField(blank=True, null=True)),
                ('light_sleep_min', models.IntegerField(blank=True, null=True)),
                ('rem_sleep_min', models.IntegerField(blank=True, null=True)),
                ('sleep_efficiency', models.IntegerField(blank=True, null=True)),
                ('sleep_score', models.IntegerField(blank=True, null=True)),
                ('sleep_start_time', models.TimeField(blank=True, null=True)),
                ('sleep_end_time', models.TimeField(blank=True, null=True)),
                ('steps', models.IntegerField(blank=True, null=True)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('active_zone_minutes', models.IntegerField(blank=True, null=True)),
                ('very_active_minutes', models.IntegerField(blank=True, null=True)),
                ('moderately_active_minutes', models.IntegerField(blank=True, null=True)),
                ('lightly_active_minutes', models.IntegerField(blank=True, null=True)),
                ('sedentary_minutes', models.IntegerField(blank=True, null=True)),
                ('resting_hr', models.IntegerField(blank=True, null=True)),
                ('hrv_rmssd', models.FloatField(blank=True, null=True)),
                ('hrv_deep_rmssd', models.FloatField(blank=True, null=True)),
                ('spo2_avg', models.FloatField(blank=True, null=True)),
                ('spo2_min', models.FloatField(blank=True, null=True)),
                ('skin_temp_deviation', models.FloatField(blank=True, null=True)),
                ('readiness_score', models.IntegerField(blank=True, null=True)),
                ('stress_score', models.IntegerField(blank=True, null=True)),
                ('protein_pct', models.FloatField(blank=True, null=True)),
                ('carbs_pct', models.FloatField(blank=True, null=True)),
                ('fat_pct', models.FloatField(blank=True, null=True)),
                ('data_completeness', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', 'date'], name='core_dailys_user_id_830719_idx'), models.Index(fields=['date'], name='core_dailys_date_62de1e_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
